Repository textlint/vscode-textlint, pull requests merged in 2025-03, with the labels that each got.

#9 chore: add .github/release.yml
  .github/release.yml
Labels: Type: Meta

#10 CI: pin GitHub Action's version
  .github/workflows/integration-tests.yaml
  .github/workflows/publish.yaml
Labels: Type: CI

#6 fix: use Status.WARN instead of ERROR
  packages/textlint/src/extension.ts
Labels: Type: Bug

#7 fix: improve `.textlintignore` support using `linter.scanFilePath()` API
  packages/test/package-lock.json
  packages/test/package.json
  packages/textlint-server/src/server.ts
  packages/textlint-server/src/textlint.d.ts
Labels: Type: Bug

#8 feat: enable to emit activation events on all language files
  packages/test/.textlintrc
  packages/test/.vscode/settings.json
  packages/test/testtest.js
  packages/test/testtest.py
  packages/textlint/package.json
  packages/textlint/src/extension.ts
  packages/textlint/src/status.ts
Labels: Type: Feature

#11 chore: bump version to 0.12.0
  README.md
  package-lock.json
  packages/textlint-server/package.json
  packages/textlint/README.md
  packages/textlint/package.json
Labels: Type: Release
